### ISSUE TITLE
Unable to finetune: not a Checkpointable

### ISSUE THREAD

**Issue by chutongz** [qubvel/classification_models#33]
Thanks for the great repo!

Now I am having problem when I want to finetune with ResNet50 model and weight.

```
Traceback (most recent call last):
  File "classifier.py", line 56, in <module>
    model = keras.models.Model(inputs=[base_model.input], outputs=output)
  File "/home/zhangchutong/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 121, in __init__
    super(Model, self).__init__(*args, **kwargs)
  File "/home/zhangchutong/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 80, in __init__
    self._init_graph_network(*args, **kwargs)
  File "/home/zhangchutong/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/checkpointable/base.py", line 474, in _method_wrapper
    method(self, *args, **kwargs)
  File "/home/zhangchutong/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 274, in _init_graph_network
    self._track_layers(layers)
  File "/home/zhangchutong/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 370, in _track_layers
    layer, name='layer-%d' % layer_index, overwrite=True)
  File "/home/zhangchutong/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/checkpointable/base.py", line 720, in _track_checkpointable
    "Checkpointable.") % (type(checkpointable),))

TypeError: Checkpointable._track_checkpointable() passed type <class 'keras.engine.input_layer.InputLayer'>, not a Checkpointable.
```

I searched on the internet, some people said it might be the incompatible between tensorflow and keras but I only import keras in my code. So confusing...

python version: 3.6
tensorflow version: 1.12.0
keras version: 2.2.4

And here is my code:
```
import keras
from skimage.io import imread
from skimage.transform import resize
from classification_models.keras import Classifiers
from util.transform import *
from keras.layers import Flatten, Dense, Dropout, BatchNormalization

checkpoint_path = 'resnet50_classifier'
ResNet50, preprocess_input = Classifiers.get('resnet50')

# some data preprocessing .....

base_model = ResNet50(input_shape=(224,224,3), weights='imagenet', include_top=False)
x = Flatten()(base_model.output)
x = Dense(4096, activation='relu')(x)
x = Dropout(0.5)(x)
x = BatchNormalization()(x)
output = Dense(n_classes, activation='softmax')(x)
model = keras.models.Model(inputs=[base_model.input], outputs=output)

cp_callback = tf.keras.callbacks.ModelCheckpoint(checkpoint_path,
                                                 save_weights_only=True, 
                                                 verbose=1)
model.compile(optimizer='SGD', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit_generator(generate_arrays_from_file(train_file, batch_size=batch_size),
            samples_per_epoch=(train_num/batch_size) *batch_size, nb_epoch=10, max_q_size=100, verbose=1, nb_worker=1, callbacks=[cp_callback])
```
Any help is appreciated!

**Comment by chutongz** [comment]
I fixed this problem just added import lines like this:
`from keras.models import Model
`
and defined the model like this:
`model = Model(inputs=[base_model.input], outputs=output)`
 Now it works fine :)
