### ISSUE TITLE
[Solve]Encounter ValueError: Shapes (512,) and (3,) are incompatible while loading pre-trained weight

### ISSUE THREAD

**Issue by ytliang97** [qubvel/classification_models#55]
```
tensorflow version: 1.12.3
```

Hello, thank you for sharing your code.

The thing is, I encounter some error when I try to load pre-trained weight.

I use `resnet34` backbone. 

Model worked well before I loaded weight from your WEIGHTS_COLLECTION.

The following is the code. It can run directly.
```python

import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras import utils as keras_utils

img_input = layers.Input(shape=(512, 512, 3), name='data')
x = layers.BatchNormalization(name='bn_data', **{'axis': 1, 'momentum': 0.99, 'epsilon': 2e-5, 'center': True, 'scale': False})(img_input)
x = layers.ZeroPadding2D(padding=(3,3))(x)
x = layers.Conv2D(64, (7,7), strides=(2,2), name='conv0', **{'kernel_initializer': 'he_uniform', 'use_bias': False, 'padding': 'valid'})(x)
x = layers.BatchNormalization(name='bn0', **{'axis': 1, 'momentum': 0.99, 'epsilon': 2e-5, 'center': True, 'scale': True})(x)
x = layers.Activation('relu', name='relu0')(x)
x = layers.ZeroPadding2D(padding=(1,1))(x)
x = layers.MaxPooling2D((3,3), strides=(2,2), padding='valid', name='pooling0')(x)

if True:
#(stage, rep) = [(0, 3), (1, 4), (2, 6), (3, 3)]
# stage = 0, block = 0
#x = ResidualBlock(64, 0, 0, strides=(1,1), cut='post', attention=Attention)(x)
    shortcut = layers.Conv2D(64, (1,1), name='stage1_unit1_sc', strides=(1,1), **{'kernel_initializer': 'he_uniform', 'use_bias': False, 'padding': 'valid'})(x)
    x = layers.BatchNormalization(name='stage1_unit1_bn1', **{'axis': 1, 'momentum': 0.99, 'epsilon': 2e-5, 'center': True, 'scale': True})(x)
    x = layers.Activation('relu', name='stage1_unit1_relu1')(x)
    x = layers.ZeroPadding2D(padding=(1,1))(x)
    x = layers.Conv2D(64, (3,3), strides=(1,1), name='stage1_unit1_conv1', **{'kernel_initializer': 'he_uniform', 'use_bias': False, 'padding': 'valid'})(x)

    x = layers.BatchNormalization(name='stage1_unit1_bn2', **{'axis': 1, 'momentum': 0.99, 'epsilon': 2e-5, 'center': True, 'scale': True})(x)
    x = layers.Activation('relu', name='stage1_unit1_relu2')(x)
    x = layers.ZeroPadding2D(padding=(1,1))(x)
    x = layers.Conv2D(64, (3,3), name='stage1_unit1_conv2', **{'kernel_initializer': 'he_uniform', 'use_bias': False, 'padding': 'valid'})(x)

    x = layers.Add()([x, shortcut])

# stage = 0, block = 1
#x = ResidualBlock(64, stage, block, strides=(1, 1), cut='pre', attention=Attention)(x)
    sortcut = x
    x = layers.BatchNormalization(name='stage1_unit2_bn1', **{'axis': 1, 'momentum': 0.99, 'epsilon': 2e-5, 'center': True, 'scale': True})(x)
    x = layers.Activation('relu', name='stage1_unit2_relu1')(x)
    x = layers.ZeroPadding2D(padding=(1,1))(x)
    x = layers.Conv2D(64, (3,3), strides=(1,1), name='stage1_unit2_conv1', **{'kernel_initializer': 'he_uniform', 'use_bias': False, 'padding': 'valid'})(x)

    x = layers.BatchNormalization(name='stage1_unit2_bn2', **{'axis': 1, 'momentum': 0.99, 'epsilon': 2e-5, 'center': True, 'scale': True})(x)
    x = layers.Activation('relu', name='stage1_unit2_relu2')(x)
    x = layers.ZeroPadding2D(padding=(1,1))(x)
    x = layers.Conv2D(64, (3,3), name='stage1_unit2_conv2', **{'kernel_initializer': 'he_uniform', 'use_bias': False, 'padding': 'valid'})(x)

    x = layers.Add()([x, shortcut])

# stage = 0, block = 2
#x = ResidualBlock(64, stage, block, strides=(1, 1), cut='pre', attention=Attention)(x)
    sortcut = x
    x = layers.BatchNormalization(name='stage1_unit3_bn1', **{'axis': 1, 'momentum': 0.99, 'epsilon': 2e-5, 'center': True, 'scale': True})(x)
    x = layers.Activation('relu', name='stage1_unit3_relu1')(x)
    x = layers.ZeroPadding2D(padding=(1,1))(x)
    x = layers.Conv2D(64, (3,3), strides=(1,1), name='stage1_unit3_conv1', **{'kernel_initializer': 'he_uniform', 'use_bias': False, 'padding': 'valid'})(x)

    x = layers.BatchNormalization(name='stage1_unit3_bn2', **{'axis': 1, 'momentum': 0.99, 'epsilon': 2e-5, 'center': True, 'scale': True})(x)
    x = layers.Activation('relu', name='stage1_unit3_relu2')(x)
    x = layers.ZeroPadding2D(padding=(1,1))(x)
    x = layers.Conv2D(64, (3,3), name='stage1_unit3_conv2', **{'kernel_initializer': 'he_uniform', 'use_bias': False, 'padding': 'valid'})(x)

    x = layers.Add()([x, shortcut])

# stage = 1, block = 0
# x = ResidualBlock(128, stage, block, strides=(2, 2), cut='post', attention=Attention)(x)
    shortcut = layers.Conv2D(128, (1,1), name='stage2_unit1_sc', strides=(2,2), **{'kernel_initializer': 'he_uniform', 'use_bias': False, 'padding': 'valid'})(x)
    x = layers.BatchNormalization(name='stage2_unit1_bn1', **{'axis': 1, 'momentum': 0.99, 'epsilon': 2e-5, 'center': True, 'scale': True})(x)
    x = layers.Activation('relu', name='stage2_unit1_relu1')(x)
    x = layers.ZeroPadding2D(padding=(1,1))(x)
    x = layers.Conv2D(128, (3,3), strides=(2,2), name='stage2_unit1_conv1', **{'kernel_initializer': 'he_uniform', 'use_bias': False, 'padding': 'valid'})(x)

    x = layers.BatchNormalization(name='stage2_unit1_bn2', **{'axis': 1, 'momentum': 0.99, 'epsilon': 2e-5, 'center': True, 'scale': True})(x)
    x = layers.Activation('relu', name='stage2_unit1_relu2')(x)
    x = layers.ZeroPadding2D(padding=(1,1))(x)
    x = layers.Conv2D(128, (3,3), name='stage2_unit1_conv2', **{'kernel_initializer': 'he_uniform', 'use_bias': False, 'padding': 'valid'})(x)

    x = layers.Add()([x, shortcut])
# stage = 1, block = 1
# x = ResidualBlock(128, stage, block, strides=(1, 1), cut='pre', attention=Attention)(x)
    sortcut = x
    x = layers.BatchNormalization(name='stage2_unit2_bn1', **{'axis': 1, 'momentum': 0.99, 'epsilon': 2e-5, 'center': True, 'scale': True})(x)
    x = layers.Activation('relu', name='stage2_unit2_relu1')(x)
    x = layers.ZeroPadding2D(padding=(1,1))(x)
    x = layers.Conv2D(128, (3,3), strides=(1,1), name='stage2_unit2_conv1', **{'kernel_initializer': 'he_uniform', 'use_bias': False, 'padding': 'valid'})(x)

    x = layers.BatchNormalization(name='stage2_unit2_bn2', **{'axis': 1, 'momentum': 0.99, 'epsilon': 2e-5, 'center': True, 'scale': True})(x)
    x = layers.Activation('relu', name='stage2_unit2_relu2')(x)
    x = layers.ZeroPadding2D(padding=(1,1))(x)
    x = layers.Conv2D(128, (3,3), name='stage2_unit2_conv2', **{'kernel_initializer': 'he_uniform', 'use_bias': False, 'padding': 'valid'})(x)

    x = layers.Add()([x, shortcut])

# stage = 1, block = 2
# x = ResidualBlock(128, stage, block, strides=(1, 1), cut='pre', attention=Attention)(x)
    sortcut = x
    x = layers.BatchNormalization(name='stage2_unit3_bn1', **{'axis': 1, 'momentum': 0.99, 'epsilon': 2e-5, 'center': True, 'scale': True})(x)
    x = layers.Activation('relu', name='stage2_unit3_relu1')(x)
    x = layers.ZeroPadding2D(padding=(1,1))(x)
    x = layers.Conv2D(128, (3,3), strides=(1,1), name='stage2_unit3_conv1', **{'kernel_initializer': 'he_uniform', 'use_bias': False, 'padding': 'valid'})(x)

    x = layers.BatchNormalization(name='stage2_unit3_bn2', **{'axis': 1, 'momentum': 0.99, 'epsilon': 2e-5, 'center': True, 'scale': True})(x)
    x = layers.Activation('relu', name='stage2_unit3_relu2')(x)
    x = layers.ZeroPadding2D(padding=(1,1))(x)
    x = layers.Conv2D(128, (3,3), name='stage2_unit3_conv2', **{'kernel_initializer': 'he_uniform', 'use_bias': False, 'padding': 'valid'})(x)

    x = layers.Add()([x, shortcut])

# stage = 1, block = 3
# x = ResidualBlock(128, stage, block, strides=(1, 1), cut='pre', attention=Attention)(x)
    sortcut = x
    x = layers.BatchNormalization(name='stage2_unit4_bn1', **{'axis': 1, 'momentum': 0.99, 'epsilon': 2e-5, 'center': True, 'scale': True})(x)
    x = layers.Activation('relu', name='stage2_unit4_relu1')(x)
    x = layers.ZeroPadding2D(padding=(1,1))(x)
    x = layers.Conv2D(128, (3,3), strides=(1,1), name='stage2_unit4_conv1', **{'kernel_initializer': 'he_uniform', 'use_bias': False, 'padding': 'valid'})(x)

    x = layers.BatchNormalization(name='stage2_unit4_bn2', **{'axis': 1, 'momentum': 0.99, 'epsilon': 2e-5, 'center': True, 'scale': True})(x)
    x = layers.Activation('relu', name='stage2_unit4_relu2')(x)
    x = layers.ZeroPadding2D(padding=(1,1))(x)
    x = layers.Conv2D(128, (3,3), name='stage2_unit4_conv2', **{'kernel_initializer': 'he_uniform', 'use_bias': False, 'padding': 'valid'})(x)

    x = layers.Add()([x, shortcut])

# stage = 2, block = 0
# x = ResidualBlock(256, stage, block, strides=(2, 2), cut='post', attention=Attention)(x)
    shortcut = layers.Conv2D(256, (1,1), name='stage3_unit1_sc', strides=(2,2), **{'kernel_initializer': 'he_uniform', 'use_bias': False, 'padding': 'valid'})(x)
    x = layers.BatchNormalization(name='stage3_unit1_bn1', **{'axis': 1, 'momentum': 0.99, 'epsilon': 2e-5, 'center': True, 'scale': True})(x)
    x = layers.Activation('relu', name='stage3_unit1_relu1')(x)
    x = layers.ZeroPadding2D(padding=(1,1))(x)
    x = layers.Conv2D(256, (3,3), strides=(2,2), name='stage3_unit1_conv1', **{'kernel_initializer': 'he_uniform', 'use_bias': False, 'padding': 'valid'})(x)

    x = layers.BatchNormalization(name='stage3_unit1_bn2', **{'axis': 1, 'momentum': 0.99, 'epsilon': 2e-5, 'center': True, 'scale': True})(x)
    x = layers.Activation('relu', name='stage3_unit1_relu2')(x)
    x = layers.ZeroPadding2D(padding=(1,1))(x)
    x = layers.Conv2D(256, (3,3), name='stage3_unit1_conv2', **{'kernel_initializer': 'he_uniform', 'use_bias': False, 'padding': 'valid'})(x)

    x = layers.Add()([x, shortcut])

# stage = 2, block = 1
# x = ResidualBlock(256, stage, block, strides=(1, 1), cut='pre', attention=Attention)(x)
    sortcut = x
    x = layers.BatchNormalization(name='stage3_unit2_bn1', **{'axis': 1, 'momentum': 0.99, 'epsilon': 2e-5, 'center': True, 'scale': True})(x)
    x = layers.Activation('relu', name='stage3_unit2_relu1')(x)
    x = layers.ZeroPadding2D(padding=(1,1))(x)
    x = layers.Conv2D(256, (3,3), strides=(1,1), name='stage3_unit2_conv1', **{'kernel_initializer': 'he_uniform', 'use_bias': False, 'padding': 'valid'})(x)

    x = layers.BatchNormalization(name='stage3_unit2_bn2', **{'axis': 1, 'momentum': 0.99, 'epsilon': 2e-5, 'center': True, 'scale': True})(x)
    x = layers.Activation('relu', name='stage3_unit2_relu2')(x)
    x = layers.ZeroPadding2D(padding=(1,1))(x)
    x = layers.Conv2D(256, (3,3), name='stage3_unit2_conv2', **{'kernel_initializer': 'he_uniform', 'use_bias': False, 'padding': 'valid'})(x)

    x = layers.Add()([x, shortcut])

# stage = 2, block = 2
# x = ResidualBlock(256, stage, block, strides=(1, 1), cut='pre', attention=Attention)(x)
    sortcut = x
    x = layers.BatchNormalization(name='stage3_unit3_bn1', **{'axis': 1, 'momentum': 0.99, 'epsilon': 2e-5, 'center': True, 'scale': True})(x)
    x = layers.Activation('relu', name='stage3_unit3_relu1')(x)
    x = layers.ZeroPadding2D(padding=(1,1))(x)
    x = layers.Conv2D(256, (3,3), strides=(1,1), name='stage3_unit3_conv1', **{'kernel_initializer': 'he_uniform', 'use_bias': False, 'padding': 'valid'})(x)

    x = layers.BatchNormalization(name='stage3_unit3_bn2', **{'axis': 1, 'momentum': 0.99, 'epsilon': 2e-5, 'center': True, 'scale': True})(x)
    x = layers.Activation('relu', name='stage3_unit3_relu2')(x)
    x = layers.ZeroPadding2D(padding=(1,1))(x)
    x = layers.Conv2D(256, (3,3), name='stage3_unit3_conv2', **{'kernel_initializer': 'he_uniform', 'use_bias': False, 'padding': 'valid'})(x)

    x = layers.Add()([x, shortcut])

# stage = 2, block = 3
# x = ResidualBlock(256, stage, block, strides=(1, 1), cut='pre', attention=Attention)(x)
    sortcut = x
    x = layers.BatchNormalization(name='stage3_unit4_bn1', **{'axis': 1, 'momentum': 0.99, 'epsilon': 2e-5, 'center': True, 'scale': True})(x)
    x = layers.Activation('relu', name='stage3_unit4_relu1')(x)
    x = layers.ZeroPadding2D(padding=(1,1))(x)
    x = layers.Conv2D(256, (3,3), strides=(1,1), name='stage3_unit4_conv1', **{'kernel_initializer': 'he_uniform', 'use_bias': False, 'padding': 'valid'})(x)

    x = layers.BatchNormalization(name='stage3_unit4_bn2', **{'axis': 1, 'momentum': 0.99, 'epsilon': 2e-5, 'center': True, 'scale': True})(x)
    x = layers.Activation('relu', name='stage3_unit4_relu2')(x)
    x = layers.ZeroPadding2D(padding=(1,1))(x)
    x = layers.Conv2D(256, (3,3), name='stage3_unit4_conv2', **{'kernel_initializer': 'he_uniform', 'use_bias': False, 'padding': 'valid'})(x)

    x = layers.Add()([x, shortcut])

# stage = 2, block = 4
# x = ResidualBlock(256, stage, block, strides=(1, 1), cut='pre', attention=Attention)(x)
    sortcut = x
    x = layers.BatchNormalization(name='stage3_unit5_bn1', **{'axis': 1, 'momentum': 0.99, 'epsilon': 2e-5, 'center': True, 'scale': True})(x)
    x = layers.Activation('relu', name='stage3_unit5_relu1')(x)
    x = layers.ZeroPadding2D(padding=(1,1))(x)
    x = layers.Conv2D(256, (3,3), strides=(1,1), name='stage3_unit5_conv1', **{'kernel_initializer': 'he_uniform', 'use_bias': False, 'padding': 'valid'})(x)

    x = layers.BatchNormalization(name='stage3_unit5_bn2', **{'axis': 1, 'momentum': 0.99, 'epsilon': 2e-5, 'center': True, 'scale': True})(x)
    x = layers.Activation('relu', name='stage3_unit5_relu2')(x)
    x = layers.ZeroPadding2D(padding=(1,1))(x)
    x = layers.Conv2D(256, (3,3), name='stage3_unit5_conv2', **{'kernel_initializer': 'he_uniform', 'use_bias': False, 'padding': 'valid'})(x)

    x = layers.Add()([x, shortcut])

# stage = 2, block = 5
# x = ResidualBlock(256, stage, block, strides=(1, 1), cut='pre', attention=Attention)(x)
    sortcut = x
    x = layers.BatchNormalization(name='stage3_unit6_bn1', **{'axis': 1, 'momentum': 0.99, 'epsilon': 2e-5, 'center': True, 'scale': True})(x)
    x = layers.Activation('relu', name='stage3_unit6_relu1')(x)
    x = layers.ZeroPadding2D(padding=(1,1))(x)
    x = layers.Conv2D(256, (3,3), strides=(1,1), name='stage3_unit6_conv1', **{'kernel_initializer': 'he_uniform', 'use_bias': False, 'padding': 'valid'})(x)

    x = layers.BatchNormalization(name='stage3_unit6_bn2', **{'axis': 1, 'momentum': 0.99, 'epsilon': 2e-5, 'center': True, 'scale': True})(x)
    x = layers.Activation('relu', name='stage3_unit6_relu2')(x)
    x = layers.ZeroPadding2D(padding=(1,1))(x)
    x = layers.Conv2D(256, (3,3), name='stage3_unit6_conv2', **{'kernel_initializer': 'he_uniform', 'use_bias': False, 'padding': 'valid'})(x)

    x = layers.Add()([x, shortcut])

# stage = 3, block = 0
# x = ResidualBlock(512, stage, block, strides=(2, 2), cut='post', attention=Attention)(x)
    shortcut = layers.Conv2D(512, (1,1), name='stage4_unit1_sc', strides=(2,2), **{'kernel_initializer': 'he_uniform', 'use_bias': False, 'padding': 'valid'})(x)
    x = layers.BatchNormalization(name='stage4_unit1_bn1', **{'axis': 1, 'momentum': 0.99, 'epsilon': 2e-5, 'center': True, 'scale': True})(x)
    x = layers.Activation('relu', name='stage4_unit1_relu1')(x)
    x = layers.ZeroPadding2D(padding=(1,1))(x)
    x = layers.Conv2D(512, (3,3), strides=(2,2), name='stage4_unit1_conv1', **{'kernel_initializer': 'he_uniform', 'use_bias': False, 'padding': 'valid'})(x)

    x = layers.BatchNormalization(name='stage4_unit1_bn2', **{'axis': 1, 'momentum': 0.99, 'epsilon': 2e-5, 'center': True, 'scale': True})(x)
    x = layers.Activation('relu', name='stage4_unit1_relu2')(x)
    x = layers.ZeroPadding2D(padding=(1,1))(x)
    x = layers.Conv2D(512, (3,3), name='stage4_unit1_conv2', **{'kernel_initializer': 'he_uniform', 'use_bias': False, 'padding': 'valid'})(x)

    x = layers.Add()([x, shortcut])

# stage = 3, block = 1
# x = ResidualBlock(512, stage, block, strides=(1, 1), cut='pre', attention=Attention)(x)
    sortcut = x
    x = layers.BatchNormalization(name='stage4_unit2_bn1', **{'axis': 1, 'momentum': 0.99, 'epsilon': 2e-5, 'center': True, 'scale': True})(x)
    x = layers.Activation('relu', name='stage4_unit2_relu1')(x)
    x = layers.ZeroPadding2D(padding=(1,1))(x)
    x = layers.Conv2D(512, (3,3), strides=(1,1), name='stage4_unit2_conv1', **{'kernel_initializer': 'he_uniform', 'use_bias': False, 'padding': 'valid'})(x)

    x = layers.BatchNormalization(name='stage4_unit2_bn2', **{'axis': 1, 'momentum': 0.99, 'epsilon': 2e-5, 'center': True, 'scale': True})(x)
    x = layers.Activation('relu', name='stage4_unit2_relu2')(x)
    x = layers.ZeroPadding2D(padding=(1,1))(x)
    x = layers.Conv2D(512, (3,3), name='stage4_unit2_conv2', **{'kernel_initializer': 'he_uniform', 'use_bias': False, 'padding': 'valid'})(x)

    x = layers.Add()([x, shortcut])

# stage = 2, block = 2
# x = ResidualBlock(512, stage, block, strides=(1, 1), cut='pre', attention=Attention)(x)
    sortcut = x
    x = layers.BatchNormalization(name='stage4_unit3_bn1', **{'axis': 1, 'momentum': 0.99, 'epsilon': 2e-5, 'center': True, 'scale': True})(x)
    x = layers.Activation('relu', name='stage4_unit3_relu1')(x)
    x = layers.ZeroPadding2D(padding=(1,1))(x)
    x = layers.Conv2D(512, (3,3), strides=(1,1), name='stage4_unit3_conv1', **{'kernel_initializer': 'he_uniform', 'use_bias': False, 'padding': 'valid'})(x)

    x = layers.BatchNormalization(name='stage4_unit3_bn2', **{'axis': 1, 'momentum': 0.99, 'epsilon': 2e-5, 'center': True, 'scale': True})(x)
    x = layers.Activation('relu', name='stage4_unit3_relu2')(x)
    x = layers.ZeroPadding2D(padding=(1,1))(x)
    x = layers.Conv2D(512, (3,3), name='stage4_unit3_conv2', **{'kernel_initializer': 'he_uniform', 'use_bias': False, 'padding': 'valid'})(x)

    x = layers.Add()([x, shortcut])

x = layers.BatchNormalization(name='bn1', **{'axis': 1, 'momentum': 0.99, 'epsilon': 2e-5, 'center': True, 'scale': True})(x)
x = layers.Activation('relu', name='relu1')(x)

backbone = models.Model(inputs=img_input, outputs=x)


print(backbone.summary())

print(backbone.input)
print(backbone.output)
#print(backbone.get_layer(name='stage4_unit1_relu1').output)

print(backbone.layers[-1])

# load weight
WEIGHTS_COLLECTION = [
    # ResNet34
    {
        'model': 'resnet34',
        'dataset': 'imagenet',
        'classes': 1000,
        'include_top': True,
        'url': 'https://github.com/qubvel/classification_models/releases/download/0.0.1/resnet34_imagenet_1000.h5',
        'name': 'resnet34_imagenet_1000.h5',
        'md5': '2ac8277412f65e5d047f255bcbd10383',
    },

    {
        'model': 'resnet34',
        'dataset': 'imagenet',
        'classes': 1000,
        'include_top': False,
        'url': 'https://github.com/qubvel/classification_models/releases/download/0.0.1/resnet34_imagenet_1000_no_top.h5',
        'name': 'resnet34_imagenet_1000_no_top.h5',
        'md5': '8caaa0ad39d927cb8ba5385bf945d582',
    }
]
w = list(filter(lambda x: x['model'] == 'resnet34', WEIGHTS_COLLECTION))
w = list(filter(lambda x: x['dataset'] == 'imagenet', w))
w = list(filter(lambda x: x['include_top'] == False, w))
print(w)

weights = w[0]

weights_path = keras_utils.get_file(
    weights['name'],
    weights['url'],
    cache_subdir='modelssssss',
    md5_hash=weights['md5']
)

backbone.load_weights(weights_path)
```

and I got the information:
```
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to
==================================================================================================
** IGNORE LAYER
==================================================================================================
Total params: 21,281,856
Trainable params: 21,276,544
Non-trainable params: 5,312
__________________________________________________________________________________________________
None
Tensor("data:0", shape=(?, 512, 512, 3), dtype=float32)
Tensor("relu1/Relu:0", shape=(?, 16, 16, 512), dtype=float32)
<tensorflow.python.keras.layers.core.Activation object at 0x1281255c0>
[{'model': 'resnet34', 'dataset': 'imagenet', 'classes': 1000, 'include_top': False, 'url': 'https://github.com/qubvel/classification_models/releases/download/0.0.1/resnet34_imagenet_1000_no_top.h5', 'name': 'resnet34_imagenet_1000_no_top.h5', 'md5': '8caaa0ad39d927cb8ba5385bf945d582'}]
Traceback (most recent call last):
  File "flatten_model_of_resnet34_unet.py", line 307, in <module>
    backbone.load_weights(weights_path)
  File "/usr/local/Cellar/python@3.6/3.6.9_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1544, in load_weights
    saving.load_weights_from_hdf5_group(f, self.layers)
  File "/usr/local/Cellar/python@3.6/3.6.9_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/keras/engine/saving.py", line 806, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "/usr/local/Cellar/python@3.6/3.6.9_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 2779, in batch_set_value
    assign_op = x.assign(assign_placeholder)
  File "/usr/local/Cellar/python@3.6/3.6.9_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 951, in assign
    self._shape.assert_is_compatible_with(value_tensor.shape)
  File "/usr/local/Cellar/python@3.6/3.6.9_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py", line 848, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (512,) and (3,) are incompatible
```
I have changed input shape with (256, 256, 3), (224, 224, 3), (512, 512, 3), (512, 512, 1), but it doesn't work.
And I already google for a while, but I still don't know how to solve this problem.

Could anyone give me advice? Thank you!

**Comment by ytliang97** [comment]
I solve the problem.

Backend default is channel last. (B, H, W, C)

axis is an argument of BatchNorm and Concatenate.

axis = 1 refers to channel first (B, C, H, W)
axis = 3 refers to channel last (B, H, W, C)

I set channel last for input shape.

```python
img_input = layers.Input(shape=(512, 512, 3), name='data')
```
 
But I set channel first for batchnorm and concatenate.

```python
x = layers.BatchNormalization(name='bn_data', **{'axis': 1, 'momentum': 0.99, 'epsilon': 2e-5, 'center': True, 'scale': False})(img_input)
```
